import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display, Dancing_Script, Lora, Allura } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const kredit = localFont({
  src: "./fonts/KreditFront.otf",
  variable: "--font-kredit",
  display: "swap",
  fallback: ["Arial", "sans-serif"],
});

// La Luxes font alternatives using Google Fonts
// Using Playfair Display (elegant serif) and Dancing Script (elegant script) as alternatives
// If you have the actual La Luxes font files, you can replace these with localFont
const laLuxesScript = Dancing_Script({
  subsets: ["latin"],
  variable: "--font-la-luxes-script",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

const laLuxesSerif = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-la-luxes-serif",
  display: "swap",
  weight: ["400", "500", "600", "700", "800", "900"],
});

// Additional fonts for v3
const lora = Lora({
  subsets: ["latin"],
  variable: "--font-lora",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

const allura = Allura({
  subsets: ["latin"],
  variable: "--font-allura",
  display: "swap",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${kredit.variable} ${laLuxesScript.variable} ${laLuxesSerif.variable} ${lora.variable} ${allura.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
